# Generated by Django 5.1.2 on 2024-11-01 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'TITLE', 'verbose_name_plural': 'TEXT'},
        ),
    ]
